name: foundation_2
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.7
  dart_code_metrics: 5.7.2
  dimind_analysis:
    path: ./packages/dimind_analysis
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
